### ISSUE TITLE
backend check for fobidden symbols in user nickname

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#224]
Please check if backend insures than user nickname doesn't contain the following symbols while creating and modifying it: { } < # > ^ " ' $ % . \\ | / ? * + ( ) space

(!newValue.match(/[%'<#>\$|/?* +^.(){}"]/))

**Comment by benjaminbrassart** [comment]
https://github.com/benjaminbrassart/transcendence/blob/01f064ea31064fa80656c01a69f0c5e097e9d200/backend/src/user/dto/setNickname.dto.ts#L4

Note to self, change this regex
