### ISSUE TITLE
Error console in tchat

### ISSUE THREAD

**Issue by Balgor18** [benjaminbrassart/transcendence#226]
Error appears on console when someone create a channel.
![image](https://user-images.githubusercontent.com/49709897/227784122-70361a18-fb26-4c38-b45a-1c96a69eb15f.png)

**Comment by BarbaraC12** [comment]
I found this error in master but not in bcano-chat branch

**Comment by daisvke** [comment]
![2023-03-28 15_14_55-xubuntu (Instantané 1)  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/65622360/228248464-45039641-bf97-4dc3-bba0-ab097b7371eb.png)

![2023-03-28 15_16_09-xubuntu (Instantané 1)  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/65622360/228248816-86dbd880-ced2-41b3-959b-a969801f24f4.png)


Doesn't it say here that it comes from Chat.tsx:234 ?

**Comment by daisvke** [comment]
![2023-03-28 18_23_26-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/65622360/228305711-9f1962c8-b5b2-42ae-b739-659ee7d46636.png)

We also have this one, whenever you send a message

**Comment by BarbaraC12** [comment]
> 
i've this message to but we don't have Fragment component anymore

**Comment by daisvke** [comment]
In regards to what [Balgor18](https://github.com/Balgor18) said earlier:
"Daisuke, what do you understand on the project and with your cursus at 42. For real, i think nothing or 2, 3 things but not more."
I think he should do it himself.

**Comment by BarbaraC12** [comment]
fix in responsive-chat
