### ISSUE TITLE
Player left the game

### ISSUE THREAD

**Issue by Balgor18** [benjaminbrassart/transcendence#227]
I dont know if is it possible. But if somone launch a game vs a IA or a random people. If somone change the URL(For example in chat page). It is possible to send in backend something for a user to left the game.

**Comment by jesuisstan** [comment]
I performed some useLocation aproach to control on which page the user is located at the moment 

![Screenshot from 2023-03-28 02-53-34](https://user-images.githubusercontent.com/82715902/228099039-007c3de9-976c-474e-9163-72070810c802.png)

You can add socket and send some sign to backend in this useEffect. Does this suit you or need something more specific?

**Comment by Balgor18** [comment]
![image](https://user-images.githubusercontent.com/49709897/228205739-34372bf3-91fb-486d-a97e-a90ac8288487.png)
I need something like that. But i need to know if the user is currently playing a game.

**Comment by jesuisstan** [comment]
Is there any kind of "live game status" on backend? How backend knows that this time the game is playing?

**Comment by Balgor18** [comment]
The system of the picture work but the socket witch one a emit dosent work on back. I need to check why.
