### ISSUE TITLE
Teammates details for the Home page

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#231]
Please provide your "catch phrase" and "responsibilities" to fill your <Peer /> components on Home page.
![Screenshot from 2023-03-26 20-06-48](https://user-images.githubusercontent.com/82715902/227795312-65d704e9-0667-418e-9a81-07eb255b2fda.png)

**Comment by Balgor18** [comment]
When Daisuke wrote his catch phrase. Go merge.

**Comment by BarbaraC12** [comment]
I will change mine to ^^'
We can't keep "I made this shit and i wanna die "
Daisuke can you change mine too by "We did It!" please ?

**Comment by daisvke** [comment]
Done!
