### ISSUE TITLE
Unauthorized error on first load

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#235]
On the first load of our App (or if no user logged in) we get a console error:

![Screenshot from 2023-03-27 14-52-05](https://user-images.githubusercontent.com/82715902/227945026-9444f650-1c49-4d49-b400-748f301b5db1.png)

from this part of the code

![Screenshot from 2023-03-27 14-53-12](https://user-images.githubusercontent.com/82715902/227945221-93b989c9-d687-426c-8455-4e7aff42c5d3.png)

Can you modify the server-side code to handle unauthenticated requests and return an appropriate response code instead of throwing an error. This will prevent the error from occurring in the first place.

**Comment by Balgor18** [comment]
This error appears because the user it not login. So we return a 401 because of that. Its a normal response

**Comment by benjaminbrassart** [comment]
this is the expected behavior, the error is properly handled by the frontend
