### ISSUE TITLE
Auto logout drops the server

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#240]
Noticed that when auto logout happens, you cannot login again. 
Receiving: "This site (http://localhost:3080/auth/42)  can’t be reached"

**Comment by Balgor18** [comment]
I can't reproduce the bug

**Comment by jesuisstan** [comment]
Well, just after passing some time (maybe 30 minutes) after non using the App, when user auto logged out, I tried to login again and cannot do it neighter with github nor with 42. Cought this issue for several times

**Comment by Balgor18** [comment]
Ok , i do a magic trick and normally now you dont be logout after times

**Comment by jesuisstan** [comment]
![Screenshot from 2023-03-28 22-08-35](https://user-images.githubusercontent.com/82715902/228355142-5649bb10-2e23-46b2-a48c-daed23b095a3.png)

**Comment by jesuisstan** [comment]
Postponing auto logout from 1h to 15h works to pass an inattentive evaluator. What if someone decided to adjust this time and test? Unfortunately this bug crashes the App, it needs to be handled in a proper way

**Comment by benjaminbrassart** [comment]
> What if someone decided to adjust this time and test?

That's our app and we decide what time is best

> Unfortunately this bug crashes the App, it needs to be handled in a proper way

Agreed. Can you provide some stack trace?

**Comment by Balgor18** [comment]
> Agreed. Can you provide some stack trace?
Is inside the websocket.service when i call the vrify function of jwtservice, and the token expired he create a error

**Comment by Balgor18** [comment]
Ok we can have 2 differents ways to fix this. 

First one. we create a refresh token that we send to the user. When the first one is expired we resend a new token available.

The second one, is 
![image](https://user-images.githubusercontent.com/49709897/228614796-4548df6b-fa4e-4711-a168-65aa9c43d804.png)
 to catch with the socker the gateway 'error'. And print to the user is disconnect and redirect it to the login page. Not really great but already code.
