### ISSUE TITLE
win score defining

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#247]
Need to emplement win score defining at least for single player and custom multiplayer games. For now win score is hardcoded: 

![Screenshot 2023-03-28 160859](https://user-images.githubusercontent.com/82715902/228265528-e818d0a6-bcf0-4324-b0e2-79c136f894ca.png)

Default value is 5. The one who invites for the game should be allowed to choose the score before game starts.

**Comment by Balgor18** [comment]
I'm gonna send you the win score with the socket.
But for that i need to test he mach invitation implementation.
And the that i need some little button with the friends for tried this.

**Comment by jesuisstan** [comment]
On what page or popup you need this button? What's the functional of the button?

**Comment by Balgor18** [comment]
When you click on a friends. we can spectate the game (1 button), If the friends is online match invitation( 1 other button)
