### ISSUE TITLE
Bonus mode (obstacle moves) for custom mode

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#248]
Need to emplement additional "map" with moving obstacle at least for single player and maybe for custom multiplayer modes. 
Physics already written in Pong.tsx file on game_on_front branch:

![Screenshot 2023-03-28 161853](https://user-images.githubusercontent.com/82715902/228268782-9ffff6f3-c64e-4396-b766-d1187bba19e1.png)

**Comment by Balgor18** [comment]
Can we just finishe the project

**Comment by jesuisstan** [comment]
It's madtatory part:
![Screenshot from 2023-03-28 17-40-19](https://user-images.githubusercontent.com/82715902/228292243-d2c7a39a-d1d1-46f4-ad9f-c99022193d74.png)

**Comment by Balgor18** [comment]
The ia counts as a custom

**Comment by Balgor18** [comment]
Working on the issue #247 and this one
