### ISSUE TITLE
Match abort set result work

### ISSUE THREAD

**Issue by Balgor18** [benjaminbrassart/transcendence#251]
Check the branch for modif

**Comment by Balgor18** [comment]
Im not gonna make the pull request. Check if is what you need @jesuisstan.

**Comment by jesuisstan** [comment]
Front receives the result twice in the end of aborted match. First time array with resukt containes correct reason. But the second (and pointless) received array coinaines wrong reason but correct score. The second array is used for rendering -> wrong VictoryModal data.

![Screenshot from 2023-04-02 00-49-27](https://user-images.githubusercontent.com/82715902/229319734-55654a11-5996-441e-b74e-19665d2bbc1c.png)
