### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#267]
Error happens when applying to "backendAPI.get(`/user/${playerNickname}`)" after refrashing the PlayerCard page on actual Master branch version.

![Screenshot from 2023-03-30 16-34-51](https://user-images.githubusercontent.com/82715902/228871563-cbc09deb-b739-4a2a-a467-ba3c1858030c.png)

No possobility to login again after that. 

![Screenshot from 2023-03-30 16-40-07](https://user-images.githubusercontent.com/82715902/228872364-0f19ae89-47cf-473e-9adf-566c2f2a2cc6.png)

**Comment by jesuisstan** [comment]
docker logs -f backend:

![image](https://user-images.githubusercontent.com/82715902/228883722-3475a48e-eb6c-445e-bd30-851daafaf76e.png)

**Comment by Balgor18** [comment]
Sane that #256
