### ISSUE TITLE
ServerSide check for forbidden chars in nickname is not complite

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#334]
Add ^ ` and \ as forbidden symbols for server side check:

![Screenshot from 2023-04-05 14-23-56](https://user-images.githubusercontent.com/82715902/230079411-d1557970-d0ef-41a5-b02f-c0a6fc772b0a.png)

![Screenshot from 2023-04-05 14-25-54](https://user-images.githubusercontent.com/82715902/230079867-ce7195a0-6740-41ae-beb4-5c072aa489a9.png)

![Screenshot from 2023-04-05 14-26-32](https://user-images.githubusercontent.com/82715902/230080014-dac92655-8b9e-4d40-a29f-a54968fa7412.png)

**Comment by jesuisstan** [comment]
@benjaminbrassart R U working on it?

**Comment by benjaminbrassart** [comment]
> @benjaminbrassart R U working on it?

Currently no

**Comment by jesuisstan** [comment]
Fixed? @benjaminbrassart
