### ISSUE TITLE
Restyle the Chat page

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#349]
Chat page components should look as "like on other pages" as possible.

1) make popups on Chat page look the same as popups on other pages.
I used one style for all.
take as example popup (=Modal) from src/components/profile/Enable2fa.tsx. 
Colors and styles are in src/UI/MUIstyles.ts and src/UI/colorsPong.ts.

Now: 
![Screenshot from 2023-04-05 18-42-55](https://user-images.githubusercontent.com/82715902/230147919-a2095740-cf0e-4834-8f92-6ff1edc94164.png)

Should be like: 
![Screenshot from 2023-04-05 18-43-56](https://user-images.githubusercontent.com/82715902/230148105-3f866c43-bfce-4806-890e-39a03f1cb38c.png)

2) Pay attension on Footer. It's squashed by main component. 

3) Fix the max width of chat component. Now it is smeared through all the page width on wide screens.

**Comment by BarbaraC12** [comment]
ok it's done i will stand to D for merge with responsive-chat
