### ISSUE TITLE
modify onUnBlockClick & onBlockClick

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#381]
These 2 'chat' functions are used to block/unblock players in PlayerCard.tsx: 

![Screenshot from 2023-04-11 05-42-33](https://user-images.githubusercontent.com/82715902/231050746-56819585-89b9-4de7-bc62-ad2dfe3e9cf0.png)

However their current implementation doesn't return any response or error. That's why I cannot even receive any sign about how executing ended.
Async function should return Promise with resolve & reject status. Please modify these two functions so that they at least signal about failure. 

As an example of correct implementation you can take this (file frontend/src/components/game/invitation/InvitationSendModal.tsx):

![Screenshot from 2023-04-11 05-52-38](https://user-images.githubusercontent.com/82715902/231051775-47e7ec2e-957b-428e-a9a6-aa68693ddd14.png)

**Comment by daisvke** [comment]
There are a lot of ways to manage Promises. I will improve the error handling soon. In any case, the blockClick issue has been solved.
It was due to the lack of the usage of setUser() right after the modification, which is needed to perform the update of the context.
