### ISSUE TITLE
Invitation + unBlockUser !== love

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#386]
Case:
- P11 blocks P22. ->
-  P11 right after that UNblocks P22. ->
- P22 sends invitation to P11 (P22 hasn't refrashed the page) ->
- P22 anyway receives errorAlert "P11 refused your invitation" (even though P22 isn't blocked by P11 anymore). (!) P22 is supposed to await while P11 is deciding what to do with this invitation but not to receive an error. 
- Meanwhile P11 receives game invitation from P22 (how it should be actually), accepts it ->

![Screenshot from 2023-04-11 21-03-50](https://user-images.githubusercontent.com/82715902/231263728-4cda3585-316c-47de-a5dd-c197a33983fc.png)

- Both are proceeding to game but get empty game screen and after that server drops 

![Screenshot from 2023-04-11 20-38-22](https://user-images.githubusercontent.com/82715902/231264395-73cbf2f6-147d-49ea-b297-81828053d109.png)

**Comment by Balgor18** [comment]
Weird I'm gonna check

Le mar. 11 avr. 2023 à 21:11, Stan Krivtsoff ***@***.***> a
écrit :

**Comment by daisvke** [comment]
I fixed the issue concerning the user context not being updated. I'll push a first draft in a few minutes but don't complain if it's messy I'll modify later. You can then perform your tests again but I guess it's gonna work.

**Comment by daisvke** [comment]
Did the same test, and it works. This is solved.

**Comment by jesuisstan** [comment]
Did the same test, and it does not work. Reopened, sorry

/mnt/nfs/homes/acaren/Videos/Screencasts/Screencast from 04-12-2023 05:14:34 PM.webm

**Comment by Balgor18** [comment]
I check the both example. I implement for the both case. Can you check @jesuisstan @daisvke ? If is good for you we can make the PR.

**Comment by daisvke** [comment]
I've redone the test just now after fetching the updates and make re. And it still doesn't work. However, at least there's no major error making the backend freeze, so i guess it's good enough for the evaluation, considering that the evaluator hasn't seen this page.

**Comment by Balgor18** [comment]
I just removed my previous modification. But now the error is from the front. Like when the user receive the invitation you go inside this function 
![image](https://user-images.githubusercontent.com/49709897/232321581-d6b8f196-7394-42fd-bb3b-f8db7cc7f947.png)
but is going inside 4 time 
![image](https://user-images.githubusercontent.com/49709897/232321684-10552059-2a14-42a4-a1f3-c0079591fdd0.png)
And inside 1 of this 4 time. He have the data the previous data of the blocked user.
![image](https://user-images.githubusercontent.com/49709897/232321802-ffd43aac-0a8d-4539-9050-1a82f286b2d9.png)
