### ISSUE TITLE
Loser doesn't receive gameResult

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#388]
When player refreshes the page during a match, he loses the match automaticly, but don't receives the result -> no modal with results popes up on his screen.

Espessially for receiving results on any screen I created <GameResultContext> for the App. So, 'gameResult' is global var and we need to save or reset it's state on refreshing the page.

![Screenshot from 2023-04-12 17-43-00](https://user-images.githubusercontent.com/82715902/231510700-dfa6ee46-b500-47ba-81df-2aa37e9bccf4.png)

**Comment by Balgor18** [comment]
When he refresh the page the socket is automaticly disconnect and reconnect. But during the time the match_result is send. So when is reload the page the frontend reload all the heap allocation so the data is loses. Do you really need it ?

**Comment by jesuisstan** [comment]
Well, it you can for example save the last game result for the user and send it to front in case of he left the last game by refreshing or closing the page, it would be really cool. I mean it would be proper

**Comment by jesuisstan** [comment]
'the winner takes it all'
