### ISSUE TITLE
Handle eslint warnings in Chat

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#390]
- in frontend folder run "npm start" (don't compile project before)
- you will get "Compiled with warnings". Follow the hints and correct Chat code to avoid these warnings. They all are just about syntax or 'never used' values.

[Screencast from 04-12-2023 08:04:45 PM.webm](https://user-images.githubusercontent.com/82715902/231545854-4f0b20f6-c5d0-4484-af6b-de20a76501bd.webm)

!!! Be very accurate with useEffect warnings. Sometimes it's better to leave them as it is. But handle all the rest please

**Comment by jesuisstan** [comment]
Leave useEffect warning without modifications

**Comment by BarbaraC12** [comment]
ok it's done
