### ISSUE TITLE
VIP default chatroom

### ISSUE THREAD

**Issue by daisvke** [benjaminbrassart/transcendence#393]
So @BarbaraC12 you have chosen to display a pre-existing password protected chatroom, and that's interesting.
But the thing is, you set its password in the front and don't crypt it with bcrypt, which means that, when bcrypt is going to compare the pwd from the databse with the input pwd, it is going to compare them through bcrypt, so since your pwd is not encrypted it is never going to match. Do you really need that ?

**Comment by BarbaraC12** [comment]
i'm already on it
