### ISSUE TITLE
Error displaying on the frontend

### ISSUE THREAD

**Issue by daisvke** [benjaminbrassart/transcendence#395]
![2023-04-16 01_59_57-xubuntu (Instantané 1)  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/65622360/232259148-1df602f3-5d63-4272-9324-ef38536eb591.png)

Can't we just use this Exception listener to open a popup on each WsException, instead of handling each of them separately, like you did with the checkPassword event ? So for each error from the backend, we would have that popup on the front instead of the console.log.

The error message is inside res.msg.

Because for now only a few errors are displayed.

**Comment by BarbaraC12** [comment]
@daisvke no we can't for now because we need a return code (like 409) for send the right popUp.
After that's your part you know it better than me, if you think it's cleaner going through WsException to display its messages, I'll let you do it.

**Comment by daisvke** [comment]
Do you mean that you absolutely want a http defined error code ? The way I see it, the error managing system of the app should not be a subset of the http protocol, as it could get messy + it is not important how we transfer error msg between server/client, as long it has its own logic. Giving an http like error code to each error happening inside the server is just a waste of time to me. 

So if you agree with this, I would just need a general error displayer that would take the msg as an argument and display it inside a popup window, or anything else.

**Comment by BarbaraC12** [comment]
the error code only serves me to differentiate them, the numbers don't matter yes :)

**Comment by daisvke** [comment]
Perfect then please tell me when you push that global error displaying function
