### ISSUE TITLE
X Close button in chat room does nothing

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#418]
Clicking on X Close button in chat room makes no event.

As an option: get rid of it at all

[Screencast from 04-24-2023 06:04:12 PM.webm](https://user-images.githubusercontent.com/82715902/234053602-c3c38932-ce24-465d-8a05-044fc1b5e0a2.webm)

**Comment by BarbaraC12** [comment]
Close button is doing exactly what i want, close the modal

**Comment by jesuisstan** [comment]
well, it was not obvious
