### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#421]
Just created App build with 'docker-compose up --build' and tried to play 3 games. As a result:

![Screenshot from 2023-04-25 16-00-31](https://user-images.githubusercontent.com/82715902/234300765-ec10ef5a-588e-42ca-8357-6111aec7ee8c.png)

To save time, just in case:

![Screenshot from 2023-04-25 16-02-15](https://user-images.githubusercontent.com/82715902/234301349-17924d39-a0f3-4dcc-a536-c62d0e6eb1db.png)

**Comment by Balgor18** [comment]
Witch branch ?

**Comment by Balgor18** [comment]
Can't repodruice this. I think the computer got an update on the same time
