### ISSUE TITLE
endless lines in chat

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#425]
issue:

[Screencast from 04-25-2023 06:32:25 PM.webm](https://user-images.githubusercontent.com/82715902/234343468-5c90f48b-46c2-417a-8b2b-d2095d886c70.webm)

**Comment by jesuisstan** [comment]
addition to the same issue: 

[Screencast from 04-25-2023 07:45:03 PM.webm](https://user-images.githubusercontent.com/82715902/234359385-9bcc8843-25dd-4857-844e-4442359af19f.webm)

**Comment by BarbaraC12** [comment]
![image](https://user-images.githubusercontent.com/55756205/234598942-98c3ff0a-4059-4ca6-849d-2af2118b04e9.png)

**Comment by BarbaraC12** [comment]
resolved
