### ISSUE TITLE
Autoscroll for new messages 

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#426]
Add autoscrolling for chat messages when number of received or sent messages is more than chat window can accommodate

**Comment by jesuisstan** [comment]
[Screencast from 04-25-2023 07:40:50 PM.webm](https://user-images.githubusercontent.com/82715902/234358441-86b6bf46-c42a-4618-b93f-eabbfb16db61.webm)

**Comment by BarbaraC12** [comment]
to test  before merge
[Screencast from 04-26-2023 06:15:21 PM.webm](https://user-images.githubusercontent.com/55756205/234638066-df322997-f280-44f7-b4fc-06295a9936d3.webm)

**Comment by jesuisstan** [comment]
Yeah, looks as expected. Fine

**Comment by jesuisstan** [comment]
Don't see any autoscroll added on MAster.
Moreover you returned back to an incorrect aproach on rendering Chat.tsx. Now it's again rerendering infinitly. Just add console.log to Chat.tsx and you'll see it. Return back useEffect depended on socketEvent! Current code is unacceptable and will lead to lack of memory or any other undefined behavior and fail as follows

**Comment by daisvke** [comment]
As for me, I saw an autoscroll.
But everything is very messy, and everything is, like you're saying, rendering indefinitely. Not only what you are mentioning but also the side menu.

**Comment by BarbaraC12** [comment]
We abandon the idea of ​​implementing autoscroll.   
With infinite rendering it's impossible or you'll have to rework the whole chat.
