### ISSUE TITLE
Unfollow friends doesn't work

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#428]
Unfollowing player doesn't work 

[Screencast from 04-25-2023 09:01:58 PM.webm](https://user-images.githubusercontent.com/82715902/234377752-f8896ad7-3a09-4c91-b0f6-6f6cdf01ba14.webm)

**Comment by jesuisstan** [comment]
well, the problem was because of changed endpoint name from '/friend/remove{nickname}' to '/friend/remove**/**{nickname}'.
If you have changed any other endpoints let me know to correct requests.

**Comment by Balgor18** [comment]
My bad a was thinking you use the other endpoint
