### ISSUE TITLE
Refreshing chatlist

### ISSUE THREAD

**Issue by jesuisstan** [benjaminbrassart/transcendence#437]
I fixed the issue about unacceptable everlasting chat rerendering by adding new useEffect to Chat component: 

![image](https://user-images.githubusercontent.com/82715902/235002118-a765900f-28fe-4573-b18e-a3229c2e1914.png)

This aproach makes Chat redrering in proper way BUT! Now, @BarbaraC12, you need to add to this useEffect dependency on new socketEvent. As an example use file PlayerCard.tsx:

![Screenshot from 2023-04-28 00-13-50](https://user-images.githubusercontent.com/82715902/235002601-c6e65a62-49ff-4bbf-90ec-eb5f227884be.png)

Create new var:   const [socketEvent, setSocketEvent] = useState(0);
You need to ask for a **new socket event** from backend (@daisvke ). Name it, I dont know, 'new_chat_created'. This event would be about any new chat room created. If someone created a new chat, you should increment new var "socketEvent" and rerender Chat page.

**Comment by daisvke** [comment]
The event listener is already there.

**Comment by jesuisstan** [comment]
Great. So, @BarbaraC12 , use it in a proper way

**Comment by jesuisstan** [comment]
UPDATE: 
I fixed refreshing chat list. Pull update from Master. But check if these changes doesn't crush anything in Chat. If everything is OK, comment here and I will close this issue. After that, @BarbaraC12 , you are able to fix Autoscrolling

**Comment by BarbaraC12** [comment]
I will test tomorrow

**Comment by BarbaraC12** [comment]
Seeing how the chat was set up this Issue will be dropped.   
To solve it, you will have to rework the entire chat.
